name: Apk CI

on:
  push:
    branches: [ master , 'release']
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Android Apk CI
        uses: yuanjinsongquyi/action_android_build@v1
      - name: Universal APK Builder
        uses: skywall/universal-apk-builder@v1.0.1
